# coding: utf-8

"""
    Sedaro Satellite API

     Allows for consumption of Sedaro Satellite services. Read more about Sedaro Satellite at [satellite.sedaro.com](https://satellite.sedaro.com).   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import sedaro
from sedaro.model.thermal_interface_material_update import ThermalInterfaceMaterialUpdate
from sedaro import configuration


class TestThermalInterfaceMaterialUpdate(unittest.TestCase):
    """ThermalInterfaceMaterialUpdate unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
