# coding: utf-8

"""
    Sedaro Satellite API

     Allows for consumption of Sedaro Satellite services. Read more about Sedaro Satellite at [satellite.sedaro.com](https://satellite.sedaro.com).   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import sedaro
from sedaro.model.ekf_algorithm_update import EKFAlgorithmUpdate
from sedaro import configuration


class TestEKFAlgorithmUpdate(unittest.TestCase):
    """EKFAlgorithmUpdate unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
