# coding: utf-8

"""
    Sedaro Satellite API

     Allows for consumption of Sedaro Satellite services. Read more about Sedaro Satellite at [satellite.sedaro.com](https://satellite.sedaro.com).   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import sedaro_base_client
from sedaro_base_client.model.iro_polar_circ import IROPolarCirc
from sedaro_base_client import configuration


class TestIROPolarCirc(unittest.TestCase):
    """IROPolarCirc unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
