name: Test Action

description: Runs the tests

inputs:
  python-versions:
    description: 'Python version to test'
    required: true
  host:
    description: 'Host secret'
    required: true
  api-key:
    description: 'API Key secret'
    required: true
  auth-handle:
    description: 'Auth Handle secret'
    required: true
  simplesat-a-t-id:
    description: 'SIMPLESAT A_T_ID secret'
    required: true
  simplesat-scenario-id:
    description: 'SIMPLESAT SCENARIO ID secret'
    required: true
  wildfire-a-t-id:
    description: 'WILDFIRE A_T_ID secret'
    required: true
  wildfire-scenario-id:
    description: 'WILDFIRE SCENARIO ID secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-versions }}
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Install local Sedaro package
      shell: bash
      run: |
        pip install ./sedaro

    - name: Parse and use secrets
      shell: bash
      run: |
        SECRETS=$(echo '${{ inputs.secrets-json }}' | jq -r '. | to_entries[] | "\(.key)=\"\(.value)\""')
        eval $SECRETS # Export secrets as environment variables

    - name: Create config.py
      shell: bash
      run: |
        echo "HOST = '${{ inputs.host }}'" >> tests/config.py
        echo "API_KEY = '${{ inputs.api-key }}'" >> tests/config.py
        echo "AUTH_HANDLE = '${{ inputs.auth-handle }}'" >> tests/config.py

        echo "SIMPLESAT_A_T_ID = '${{ inputs.simplesat-a-t-id }}'" >> tests/config.py
        echo "SIMPLESAT_SCENARIO_ID = '${{ inputs.simplesat-scenario-id }}'" >> tests/config.py
        echo "WILDFIRE_A_T_ID = '${{ inputs.wildfire-a-t-id }}'" >> tests/config.py
        echo "WILDFIRE_SCENARIO_ID = '${{ inputs.wildfire-scenario-id }}'" >> tests/config.py

    - name: Test with pytest
      shell: bash
      run: pytest
