from sedaro_base_client.paths.models_branches_branch_id_gnc_algorithms_thrust_control_static_thrust_control_block_id.delete import ApiFordelete
from sedaro_base_client.paths.models_branches_branch_id_gnc_algorithms_thrust_control_static_thrust_control_block_id.patch import ApiForpatch


class ModelsBranchesBranchIdGncAlgorithmsThrustControlStaticThrustControlBlockId(
    ApiFordelete,
    ApiForpatch,
):
    pass
