from sedaro_base_client.paths.models_branches_branch_id_gnc_algorithms_attitude_determination_triad_block_id.delete import ApiFordelete
from sedaro_base_client.paths.models_branches_branch_id_gnc_algorithms_attitude_determination_triad_block_id.patch import ApiForpatch


class ModelsBranchesBranchIdGncAlgorithmsAttitudeDeterminationTriadBlockId(
    ApiFordelete,
    ApiForpatch,
):
    pass
