# coding: utf-8

# flake8: noqa

"""
    Sedaro Satellite API

     Allows for consumption of Sedaro Satellite services. Read more about Sedaro Satellite at [satellite.sedaro.com](https://satellite.sedaro.com).   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from sedaro_old.api_client import ApiClient

# import Configuration
from sedaro_old.configuration import Configuration

# import exceptions
from sedaro_old.exceptions import OpenApiException
from sedaro_old.exceptions import ApiAttributeError
from sedaro_old.exceptions import ApiTypeError
from sedaro_old.exceptions import ApiValueError
from sedaro_old.exceptions import ApiKeyError
from sedaro_old.exceptions import ApiException
