# coding: utf-8

"""
    Sedaro Satellite API

     Allows for consumption of Sedaro Satellite services. Read more about Sedaro Satellite at [satellite.sedaro.com](https://satellite.sedaro.com).   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

from sedaro_old.paths.branches_branch_idcommits_.post import CommitToBranch
from sedaro_old.paths.branches_branch_id.post import CreateBranch
from sedaro_old.paths.branches_branch_id.delete import DeleteBranch
from sedaro_old.paths.branches_branch_id.get import GetBranch
from sedaro_old.paths.branches_branch_idcommitted_.get import GetCommittedBranchData
from sedaro_old.paths.branches_branch_idsaved_.get import GetSavedBranchData
from sedaro_old.paths.branches_current_branch_id_merge_incoming_branch_id.post import MergeBranches
from sedaro_old.paths.branches_branch_id.patch import UpdateBranch
from sedaro_old.paths.branches_branch_idshare_auth_.post import VerifyBranchPassword


class BranchesApi(
    CommitToBranch,
    CreateBranch,
    DeleteBranch,
    GetBranch,
    GetCommittedBranchData,
    GetSavedBranchData,
    MergeBranches,
    UpdateBranch,
    VerifyBranchPassword,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
