# coding: utf-8

"""
    Sedaro Satellite API

     Allows for consumption of Sedaro Satellite services. Read more about Sedaro Satellite at [satellite.sedaro.com](https://satellite.sedaro.com).   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

from sedaro_old.paths.models_branches_branch_id_system_loads_actuator_loads_.post import CreateActuatorLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_.post import CreateConstantLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_temp_control_loads_.post import CreateTemperatureControllerLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_actuator_loads_block_id.delete import DeleteActuatorLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_block_id.delete import DeleteConstantLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_temp_control_loads_block_id.delete import DeleteTemperatureControllerLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_actuator_loads_block_id.patch import UpdateActuatorLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_block_id.patch import UpdateConstantLoad
from sedaro_old.paths.models_branches_branch_id_system_loads_temp_control_loads_block_id.patch import UpdateTemperatureControllerLoad


class LoadApi(
    CreateActuatorLoad,
    CreateConstantLoad,
    CreateTemperatureControllerLoad,
    DeleteActuatorLoad,
    DeleteConstantLoad,
    DeleteTemperatureControllerLoad,
    UpdateActuatorLoad,
    UpdateConstantLoad,
    UpdateTemperatureControllerLoad,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
