# coding: utf-8

"""
    Sedaro Satellite API

     Allows for consumption of Sedaro Satellite services. Read more about Sedaro Satellite at [satellite.sedaro.com](https://satellite.sedaro.com).   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

from sedaro.paths.models_branches_branch_id_clock_configs_.post import CreateSimulationClockConfiguration
from sedaro.paths.models_branches_branch_id_clock_configs_block_id.delete import DeleteSimulationClockConfiguration
from sedaro.paths.models_branches_branch_id_clock_configs_block_id.patch import UpdateSimulationClockConfiguration


class SimulationClockConfigurationApi(
    CreateSimulationClockConfiguration,
    DeleteSimulationClockConfiguration,
    UpdateSimulationClockConfiguration,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
